import type { Vm } from "@/lib/vm";

const STOPPED_VM: Vm = {
  id: "vm-1",
  name: "web-01",
  status: "stopped",
  os: "Linux",
  mem: 2048,
  cpu: 2,
  cpu_sockets: 1,
  disk: 20,
  disk_format: 0,
  disk_cache: 0,
  net: "user",
  fw: "bios",
  hasIso: "false",
  hasDisk: "true",
  iso_path: "",
  notes: "",
  shared_folder: "",
  usb_device: "",
  usb_policy: 0,
  guest_tools: "false",
  autoprotect: "false",
  autoprotect_interval: 60,
  autoprotect_max: 10,
  hasDisk2: "false",
  disk2_size: 0,
  disk2_path: "",
  disk2_format: 0,
  hasFloppy: "false",
  floppy_path: "",
  port_forwards: "",
  tags: "",
  folder: "",
  mac: "",
  vnet: "",
  num_displays: 1,
  hasSerial: "false",
  virtio_rng: "false",
  guest_agent: "false",
  watchdog: 0,
  tpm: "false",
  secure_boot: "false",
  hyperv_enlightenments: "false",
  hugepages: "false",
  io_threads: 0,
  disk_bps_throttle: 0,
  disk_iops_throttle: 0,
  ballooning: "false",
  host_autostart: "false",
  enable_3d: "false",
  gpu_device: 2,
  display: 3,
  display_resolution: 0,
  guest_os: 0,
  audio: 0,
  boot_order: 0,
  rtc: 0,
  cpu_model: "host",
  accel: "auto",
  embed_display: "true",
  vnc_port: 5900,
  spice_port: 5901,
  favorite: "false",
  video_stream: "false",
  video_bitrate_kbps: 0,
};

/** A stopped VM as the daemon lists it, for unit tests; `overrides` replaces fields. */
export const sampleVm = (overrides: Partial<Vm> = {}): Vm => ({ ...STOPPED_VM, ...overrides });
